### PR TITLE
Add --runtime-log option

### PR DESCRIPTION
**Pull request by AMHOL**

### CODE REVIEW

**Review by ilyazub — COMMENTED** [review]
Thanks, @AMHOL!

Why do you want to change the runtime log path?

**Comment by AMHOL** [comment]
@ilyazub with my current setup, it makes it easier to cache between builds, the Rails tmp directory is wiped between builds, so storing it in a different directory makes life much easier (and cheaper).

**Comment by AMHOL** [comment]
@ilyazub is this something you'd consider merging or should I close the PR and find an alternate method?

**Review by ilyazub — APPROVED** [review]
Sounds good. @AMHOL, thanks for the explanation.

Also, `parallel_tests` have the `runtime-log` option and `turbo_tests` mirrors a part of options from it.

**Comment by AMHOL** [comment]
TY @ilyazub

**Pull request merged**
