### PR TITLE
Explicitely load ostruct so it's compatible with latest JSON gem

### PR DESCRIPTION
**Pull request by lcmen**
The latest `json` gem version (2.7.2 for the time being) no longer requires `OpenStruct` (PR: https://github.com/flori/json/pull/565/files) making this gem incompatible with it.

This PR modifies the codebase to explicitly `require 'ostruct'` so JSON gem is aware of it but most importantly it makes `OpenStruct` available in [lib/utils/hash_extension](https://github.com/serpapi/turbo_tests/blob/master/lib/utils/hash_extension.rb#L4).

### CODE REVIEW

**Review by deivid-rodriguez — APPROVED** [review]
Bundler [daily specs ](https://github.com/rubygems/rubygems/actions/runs/8562878499/job/23466959242) run into this too, thanks for fixing it!

**Review by javierjulio — APPROVED** [review]
Thanks! We ran into the following error today which this should address.

```
bundler: failed to load command: turbo_tests (/usr/local/bundle/bin/turbo_tests)
/usr/local/bundle/gems/turbo_tests-2.2.0/lib/utils/hash_extension.rb:4:in `to_struct': uninitialized constant CoreExtensions::OpenStruct (NameError)
```

**Comment by lcmen** [comment]
@javierjulio @deivid-rodriguez who can I ping to merge it and release a new version?

**Comment by bmulholland** [comment]
Closes https://github.com/serpapi/turbo_tests/issues/52, which I created because such an issue would have saved me 15 minutes (I looked only in Issues, not in PRs).

**Review by ilyazub — APPROVED** [review]
Thank you @lcmen! Looks good to me.

I added `json` gem as an explicit dependency in 0767720.

**Comment by lcmen** [comment]
Thank you @ilyazub !

**Comment by ilyazub** [comment]
Released in v2.2.1: https://rubygems.org/gems/turbo_tests/versions/2.2.1.

**Comment by hsbt** [comment]
Thanks all ❤️ (I'm maintainer of json gem)

**Comment by ilyazub** [comment]
This PR introduced a problem in Ruby-core CI: https://github.com/ruby/ruby/pull/10496.

**Comment by javierjulio** [comment]
@ilyazub I encountered the same JSON gem related error in the rspec-rails repo when submitting a PR. I resolved that issue there but instead of requiring OpenStruct, since it was only one instance, I replaced it with a Struct instead (maintainer suggestion). I wonder if it would help to do that same replacement here?

**Comment by javierjulio** [comment]
@ilyazub I have a patch in https://github.com/serpapi/turbo_tests/pull/53 ready for review that should replace the OpenStruct with a Struct instead so the `ostruct` dependency can be removed safely.

**Comment by ilyazub** [comment]
@javierjulio Makes sense. Thank you for debugging it!

> I encountered the same JSON gem related error in the rspec-rails repo when submitting a PR.

I understood the consequences (`rspec-rails`/`ruby-core` had issues), but not the actual root cause. What error it was in the `rspec-rails` repo?

**Comment by javierjulio** [comment]
@ilyazub you're welcome! It was the same error as reported here, essentially a "NameError: uninitialized constant OpenStruct" error message. This is [a failed build on rspec-rails from my first PR](https://github.com/rspec/rspec-rails/actions/runs/8581953635/job/23577103979) where that error occurred. I'm not sure I understand the root cause but it's tied to the json gem somehow. The understanding I and others came to elsewhere was it would be best to remove the OpenStruct usage rather than continue to rely on it.

**Comment by ilyazub** [comment]
Thank you @javierjulio! https://github.com/rspec/rspec-rails/pull/2755 makes total sense.

**Comment by lcmen** [comment]
Thank you guys for addressing from bigger picture perspective 🙇 . I wasn't aware of the problem in other repos.

**Pull request merged**
